Clustering
llmlks/QuakeWatch pull request #10
Opened 2020-03-12 12:36 UTC by afhuertass

Clustering feature.

2020-03-12 14:35 UTC, niklasmaki requested changes
So a few more comments about the changes in addition to the ones marked within the code:

- So apparently your linter was not working so there are a lot of PEP8 violations. I think the easiest way to fix this is open a file the linter complains about with VSCode and press ALT+SHIFT+F. VSCode should ask you if you want to install autopep8 formatter which should fix most of the issues. You can also take a look at the [PEP8 specification](https://www.python.org/dev/peps/pep-0008/).
- None of your functions have docstrings. You should add those at least to the most important ones, i.e. those that are called from other files. You can take a look at for example uploader.py for the docstring format.

After the changes I'm gonna review the code again.

2020-03-12 14:35 UTC, niklasmaki commented on components/cluster.py
> +@jit( nopython=True )
What does this do?

2020-03-12 14:35 UTC, niklasmaki commented on components/cluster.py
> +    ),
As we talked, this should probably be its own component.

2020-03-12 14:35 UTC, niklasmaki commented on components/cluster.py
> +            print("remove")
Maybe comment this one out as well, or is it needed?

2020-03-12 14:38 UTC, niklasmaki commented
And also you should fix the merge conflict (again)

2020-03-17 08:02 UTC, niklasmaki requested changes
Still some more small suggestions :)

2020-03-17 08:02 UTC, niklasmaki commented on components/cluster.py
> +    columns = ["TimeStamp", "EVENTID", "TimeStamp", "MAGNITUDE", "LATITUDE", "LONGITUDE"]
Why is there TimeStamp twice?

2020-03-17 08:02 UTC, niklasmaki commented on components/cluster.py
> +    Keyword arguments:
There should be an empty line above "Keyword arguments"

2020-03-17 08:02 UTC, niklasmaki commented on components/cluster.py
> +import dash_bootstrap_components as dbc
Imports should be divided into 3 categories: 

1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

These categories should be separated by empty lines. See [PEP8](https://www.python.org/dev/peps/pep-0008/#imports) for more information.

2020-03-17 08:02 UTC, niklasmaki commented on utils/earthquake_data.py
> +            self.data["TimeStamp"] = self.data.DateTime.values.astype(np.int64)/10**9
PEP8 lint complains that these lines are too long. Could they be divided into shorter lines? autopep8 does this automatically if you managed to install it.

2020-03-17 08:02 UTC, niklasmaki commented on views/clusterview.py
> +
Multiple PEP8 problems here as well.

2020-03-17 08:02 UTC, niklasmaki commented on components/cluster.py
> +    ),
This will be done in a separate task.

2020-03-17 08:04 UTC, niklasmaki commented on components/cluster.py
> +@jit( nopython=True )
So as I understand it, this jits the method to lower-level code that's more efficient (has to do with numba).

2020-03-18 13:02 UTC, afhuertass commented on utils/earthquake_data.py
> +            self.data["TimeStamp"] = self.data.DateTime.values.astype(np.int64)/10**9
Maybe there is a way to shorten the lines but renaming functions and changing DateTime for a shorter name but I would probably need to change other stuff... and I think is likely those lines are going to go away anyway. I couldn't get the autopep8 work :/

2020-03-18 13:54 UTC, afhuertass commented on views/clusterview.py
> +
You really do hate spaces. Fixed.

2020-03-19 06:39 UTC, niklasmaki approved these changes
I think all of the linting problems are solved now. And other changes look good as well, so feel free to merge 🙂

2020-03-19 06:40 UTC, niklasmaki commented
Although the conflicts must be fixed before merging...

2020-03-19 08:28 UTC, afhuertass commented
how can I solve the conflicts my local machine? so I can run the linter and make sure that everything stays on place.

2020-03-19 12:36 UTC, niklasmaki commented
In your local environment:

1) `git checkout clustering`
2) `git merge master`
3) Resolve the conflicts and then commit as usual. Then just `git push` and your fixes are shown here.

2020-03-19 17:52 UTC, afhuertass commented
I did a couple of large changes to merge the branches, I believe it is worth you @niklasmaki  take a look and make sure everything is fine before the merge :ok_hand:

2020-03-20 07:30 UTC, niklasmaki requested changes
Aside from the one question I had, I think the code looks fine. However, I'm unable to get the clustering to run anymore even with a small dataset and 1 day time range. My browser just hangs indefinitely. Maybe someone else could test it, it might just be my computer.

2020-03-20 07:30 UTC, niklasmaki commented on components/cluster.py
> +def compute_edges(data, df):
It's kind of weird that the df is given as an argument when the only thing it's used for is to check whether it's empty. Is it really necessary?

2020-03-20 13:41 UTC, niklasmaki commented on components/cluster.py
>          figures = get_figures(edges, df)
This logic is a bit weird in my opinion. Wouldn't something like this do the same?
```suggestion
    if df.empty:
        figures = [go.Figure()]
    else:
        edges, df = compute_edges(data)
        figures = get_figures(edges, df)
```

2020-03-20 13:55 UTC, niklasmaki approved these changes
I think it's ready to merge now :D

2020-03-20 13:59 UTC, merged