Config for displaying events with same template
llmlks/QuakeWatch pull request #26
Opened 2020-04-05 10:08 UTC by llmlks

2020-04-09 14:50 UTC, niklasmaki requested changes
I think the code changes are fine and the functionality works as it should 👍 

However, I get an error if I go to the map view with either the Basel dataset or the SCEDC dataset. Something about a missing template id.

Also another thing. If I understand correctly, when you select a template id, all the events with that template id from the entire dataset are shown. The date range the user has selected is completely ignored. This is not necessarily a problem, but it's kind of confusing. There is no way the user knows what data is shown. At least I initially thought that it only shows the event from the selected date range.

What do you think?

2020-04-09 18:03 UTC, llmlks commented
I'll look into the errors. 

I thought about the problem of what data to show, and ended up thinking that seeing only data from selected time range would be very restrictive. Though, I was actually only considering the time frame combined with the time slider and failed to take into account using only the date range. Currently, if the user selects a template ID from the configurations and applies the changes, the time configurations are ignored, and the time slider is hidden from under the map. Maybe it could be set optional (show only events in the selected time frame/ across whole dataset)? Additionally, adding some conditional stylings on the time configurations would help clarify the issue (e.g. fade them a little, or otherwise visualise they are disabled)?

2020-04-09 18:17 UTC, niklasmaki commented
Yeah, I think even a slight visual hint would be helpful for the user.
Adding more configurations might also be confusing.

On Thu, Apr 9, 2020, 21:03 Laila Melkas <notifications@github.com> wrote:

> I'll look into the errors.
>
> I thought about the problem of what data to show, and ended up thinking
> that seeing only data from selected time range would be very restrictive.
> Though, I was actually only considering the time frame combined with the
> time slider and failed to take into account using only the date range.
> Currently, if the user selects a template ID from the configurations and
> applies the changes, the time configurations are ignored, and the time
> slider is hidden from under the map. Maybe it could be set optional (show
> only events in the selected time frame/ across whole dataset)?
> Additionally, adding some conditional stylings on the time configurations
> would help clarify the issue (e.g. fade them a little, or otherwise
> visualise they are disabled)?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/llmlks/QuakeWatch/pull/26#issuecomment-611670625>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADSASYDDNUO3UQURKFRUWHTRLYEY3ANCNFSM4MARVIJA>
> .
>

2020-04-14 10:10 UTC, niklasmaki requested changes
I think that using the selected time range is a good solution. And I like disabling the timestep selector. Now it's more clear which configurations can be used with a template id.

However, the color and size dropdowns are now broken. For some reason they contain template ids as well.

Also, now I'm getting an error with the SCEDC and Otaniemi datasets:
```
Traceback (most recent call last):
  File "C:\Users\Niklas\Documents\Data Science Project I\QuakeWatch\index.py", line 44, in display_page
    return quake_map.get_layout(session_id)
  File "C:\Users\Niklas\Documents\Data Science Project I\QuakeWatch\views\quake_map.py", line 49, in get_layout
    dbc.Col(map_config.get_component(
  File "C:\Users\Niklas\Documents\Data Science Project I\QuakeWatch\components\config\map_config.py", line 32, in get_component
    size_picker.get_component(columns),
  File "C:\Users\Niklas\Documents\Data Science Project I\QuakeWatch\components\config\size_picker.py", line 21, in get_component
    options=[
TypeError: 'NoneType' object is not iterable
```

2020-04-14 10:10 UTC, niklasmaki commented on components/config/map_config.py
>      """
The templates docstring is twice here.

2020-04-19 14:25 UTC, niklasmaki approved these changes
Now everything works 👍

2020-04-20 09:45 UTC, merged