Cluster config
llmlks/QuakeWatch pull request #37
Opened 2020-04-26 19:47 UTC by afhuertass

Added text input for the threshold value as well as an apply button that needs to be pressed in order to launch the cluster computation.
I also added the loading component so now when the clusters are being computed the user can see that something is going on, and also modified some names and colors here and there.

2020-04-29 15:40 UTC, llmlks requested changes
Functionality works great, a few minor adjustments. Could you also update the clustering instructions in `instructions.md` so they reflect the current features?

2020-04-29 15:40 UTC, llmlks commented on components/cluster.py
> +        html.Div(children="Type threshold:"),
These might make more sense if they were added to the `cluster_config` component. Adding the class `config-label` to the "Type threshold" label will keep its styling consistent with the rest of the views

2020-04-29 15:40 UTC, llmlks commented on components/cluster.py
> +from dash.exceptions import PreventUpdate
This isn't used, as a few of the other imports, too. Maybe go through them and remove the unused ones

2020-04-29 15:40 UTC, llmlks commented on components/config/cluster_config.py
> +
Function docstring missing

2020-04-29 15:40 UTC, llmlks commented on components/config/date_picker.py
> +        html.Div(className='config-label', children='Select dates'),
A good change, could you change the corresponding values in the instructions, too?

2020-04-29 15:44 UTC, llmlks commented on components/config/cluster_config.py
> +        dcc.Input(id=idd, type="number",  value=1e-5),
The other configs use `dbc.Input`, so it might be a good idea here as well

2020-04-29 18:23 UTC, afhuertass commented
There is one issue I can't figure out, the size of the input box for the threshold is larger than expected, any idea how to control this? I tried wrapping it around a Div and I thought it should be the size of the date component ( that is what I see from how the component is built ) how can I fix it?

2020-04-29 18:26 UTC, llmlks commented
You could add the picker's ID to the list of element IDs in the `config.css` where the element width is defined as 288px

2020-04-29 18:27 UTC, llmlks commented
And at the same time, you could add the `Apply` buttons' IDs to the list with `#apply` to ensure there is some margin between the elements

2020-04-29 18:52 UTC, llmlks approved these changes
Happy with the changes. The branch is ready for merge once you've resolved the merge conflicts,

2020-04-30 07:24 UTC, merged

2020-04-30 08:31 UTC, llmlks commented
Is there a reason you deleted the `opacity-unit`, `opacity-value` and `template-id` stylings from `config.css` during merge? :D

2020-04-30 08:32 UTC, llmlks commented
Here's how they used to be: https://github.com/llmlks/QuakeWatch/pull/37/commits/e668016e243d736e608c6ee1e925544d420b4540

2020-04-30 11:22 UTC, afhuertass commented
ah damn that was a mistake, sorry  . how can I fix it :s

2020-04-30 11:25 UTC, llmlks commented
No worries! You can just commit the original values to this branch and make a new pull request