Map skeleton
llmlks/QuakeWatch pull request #5
Opened 2020-03-03 13:59 UTC by niklasmaki

2020-03-05 20:32 UTC, llmlks requested changes

2020-03-05 20:32 UTC, llmlks commented on components/quake_map.py
> +api_url = api_base_url + 'apikey=' + app.server.config['THUNDERFOREST_API_KEY']
Is there a reason these two are defined as separate variables?

2020-03-05 20:32 UTC, llmlks commented on views/quake_map.py
> +from app import app
These imports aren't used anywhere

2020-03-05 20:32 UTC, llmlks commented on .gitignore
> +# Config gile
Minor typo: gile > file

2020-03-07 08:55 UTC, niklasmaki commented
Made the requested changes

2020-03-07 13:25 UTC, merged

2020-03-07 13:26 UTC, niklasmaki commented
I merged the changes already because I need them for another task. If there's still some changes I should make, I'll open another pull request.